/** Curated list of employer countries (ISO name). Extend as needed. */
export const countries: string[] = [
  'South Korea',
  'Germany',
  'Japan',
  'Poland',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Turkey',
  'United Kingdom',
  'Ireland',
  'Czech Republic',
  'Slovakia',
  'Hungary',
  'Lithuania',
  'Latvia',
  'Estonia',
  'Romania',
  'Bulgaria',
  'Croatia',
  'Slovenia',
  'Austria',
  'Switzerland',
  'Netherlands',
  'Belgium',
  'France',
  'Italy',
  'Spain',
  'Portugal',
  'Greece',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Canada',
  'United States',
  'Australia',
  'New Zealand',
  'Singapore',
  'Malaysia',
  'Israel',
  'Kazakhstan',
  'Russia',
  'Azerbaijan',
  'Georgia',
  'Cyprus',
  'Malta',
  'Other',
];
